on: [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  linux-debug:
    name: Linux Debug
    runs-on: ubuntu-20.04

    env:
      CC: ccache gcc-10
      CXX: ccache g++-10
      TREAT_WARNINGS_AS_ERRORS: 1
      GEN: ninja

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install
      run: sudo apt-get install ccache

    # https://cristianadam.eu/20200113/speeding-up-c-plus-plus-github-actions-using-ccache/
    - name: Prepare cache keys
      id: date
      run: echo "::set-output name=date::$(date -Ihours)"

    - name: Cache ccache
      uses: actions/cache@v2
      with:
        path: .ccache
        key: ccache-1-${{steps.date.outputs.date}}
        restore-keys: ccache-1-

    - name: ccache status
      run: |
        ccache -s
        du -hs ~/.ccache

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. && make

    - name: ccache status
      if: always()
      run: |
        ccache -s
        du -hs ~/.ccache
